[package]
name = "pool"
version = "0.1.0"
authors = ["z0ji <zoji@maelstrom.finance>"]
edition = "2018"

[features]
no-entrypoint = []

[dependencies]
#solana related dependencies
solana-program = "1.7.10"
solana-frozen-abi = "1.7.10"
spl-token = { version = "3.1.1", features = ["no-entrypoint"] }

#serializiation/deserialzation
borsh = { version = "0.9.1", features = ["const-generics"] }
borsh-derive = "0.9.1"

#numerics
#uint = { version = "0.9.1", default-features = false }
muldiv = "1.0.0"

#error handling
thiserror = "1.0"
num-traits = "0.2"
num-derive = "0.3"

#misc
arrayvec = "0.7.1"

[dev-dependencies]
solana-program-test = "1.7.4"
solana-sdk = "1.7.4"
